# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ansible_python_interpreter: /usr/bin/python3
cloudsdk_python_export_path: /usr/bin/python3
gcloud_install_dir: /usr/local
package_list:
  - "@large-systems"
  - acl
  - uuidd
  - tcsh
  - psmisc
  - libatomic
  - numactl-libs
  - libtool-ltdl
  - nfs-utils
  - lvm2
  - autofs
  - ndctl
  - unzip
  - libsss_autofs
  - libnsl
  - autoconf.noarch
  - automake.noarch
  - cyrus-sasl.x86_64
  - expat.x86_64
  - fontconfig.x86_64
  - glibc-devel.i686
  - keyutils-libs.x86_64 
  - krb5-libs.x86_64
  - libcom_err.x86_64   
  - libidn2.x86_64
  - libselinux.x86_64
  - libxcb.i686
  - nspr.x86_64
  - nss.x86_64
  - nss-softokn.x86_64
  - nss-softokn-freebl.x86_64
  - nss-util.x86_64 
  - openldap.x86_64 
  - openssl.x86_64
  - zlib.x86_64
  - libstdc++.i686
  - libX11.i686
  - libXau.i686
  - glibc.i686
  - libstdc++.i686
  - libgcc.i686
  - libuuid.i686
  - xorg-x11-xauth
  - libXtst
  - xterm
  - libXext.i686  
  - libXcursor.i686  
  - libXrender.i686  
  - libXfixes.i686
  - xz-libs.i686
  - oracle-database-preinstall-19c
  - libxcrypt-compat
  - compat-openssl11
  - fontconfig
  - libasan
  - liblsan
  - libibverbs
  - librdmacm
  - libvirt-libs
  - libnsl2
  - gcc
  - unixODBC

